
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.maxarmory.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.Item;

import net.mcreator.maxarmory.item.WoodenShamshirItem;
import net.mcreator.maxarmory.item.WoodenPikeItem;
import net.mcreator.maxarmory.item.WoodenMacheteItem;
import net.mcreator.maxarmory.item.WoodenLongSwordItem;
import net.mcreator.maxarmory.item.WoodenKatanaItem;
import net.mcreator.maxarmory.item.WoodenHengdaoItem;
import net.mcreator.maxarmory.item.WoodenHammerItem;
import net.mcreator.maxarmory.item.WoodenHalberdItem;
import net.mcreator.maxarmory.item.StoneShamshirItem;
import net.mcreator.maxarmory.item.StonePikeItem;
import net.mcreator.maxarmory.item.StoneMacheteItem;
import net.mcreator.maxarmory.item.StoneLongSwordItem;
import net.mcreator.maxarmory.item.StoneKatanaItem;
import net.mcreator.maxarmory.item.StoneHengdaoItem;
import net.mcreator.maxarmory.item.StoneHammerItem;
import net.mcreator.maxarmory.item.StoneHalberdItem;
import net.mcreator.maxarmory.item.NethritePikeItem;
import net.mcreator.maxarmory.item.NetheriteShamshirItem;
import net.mcreator.maxarmory.item.NetheriteMacheteItem;
import net.mcreator.maxarmory.item.NetheriteLongSwordItem;
import net.mcreator.maxarmory.item.NetheriteKatanaItem;
import net.mcreator.maxarmory.item.NetheriteHengdaoItem;
import net.mcreator.maxarmory.item.NetheriteHalberdItem;
import net.mcreator.maxarmory.item.NetheriteGuduoItem;
import net.mcreator.maxarmory.item.MingguangArmorItem;
import net.mcreator.maxarmory.item.LongGripItem;
import net.mcreator.maxarmory.item.LamellarArmourPieceItem;
import net.mcreator.maxarmory.item.LamellarArmorItem;
import net.mcreator.maxarmory.item.IronShamshirItem;
import net.mcreator.maxarmory.item.IronPikeItem;
import net.mcreator.maxarmory.item.IronMacheteItem;
import net.mcreator.maxarmory.item.IronLongSwordItem;
import net.mcreator.maxarmory.item.IronKatanaItem;
import net.mcreator.maxarmory.item.IronHengdaoItem;
import net.mcreator.maxarmory.item.IronHalberdItem;
import net.mcreator.maxarmory.item.IronGuduoItem;
import net.mcreator.maxarmory.item.GripItem;
import net.mcreator.maxarmory.item.GoldenShamshirItem;
import net.mcreator.maxarmory.item.GoldenPikeItem;
import net.mcreator.maxarmory.item.GoldenMacheteItem;
import net.mcreator.maxarmory.item.GoldenLongSwordItem;
import net.mcreator.maxarmory.item.GoldenKatanaItem;
import net.mcreator.maxarmory.item.GoldenHengdaoItem;
import net.mcreator.maxarmory.item.GoldenHalberdItem;
import net.mcreator.maxarmory.item.GoldenGuduoItem;
import net.mcreator.maxarmory.item.DiamondShamshirItem;
import net.mcreator.maxarmory.item.DiamondPikeItem;
import net.mcreator.maxarmory.item.DiamondMacheteItem;
import net.mcreator.maxarmory.item.DiamondLongSwordItem;
import net.mcreator.maxarmory.item.DiamondKatanaItem;
import net.mcreator.maxarmory.item.DiamondHengdaoItem;
import net.mcreator.maxarmory.item.DiamondHalberdItem;
import net.mcreator.maxarmory.item.DiamondGuduoItem;
import net.mcreator.maxarmory.item.CopperSwordItem;
import net.mcreator.maxarmory.item.CopperShamshirItem;
import net.mcreator.maxarmory.item.CopperPikeItem;
import net.mcreator.maxarmory.item.CopperMacheteItem;
import net.mcreator.maxarmory.item.CopperLongSwardItem;
import net.mcreator.maxarmory.item.CopperKatanaItem;
import net.mcreator.maxarmory.item.CopperHengdaoItem;
import net.mcreator.maxarmory.item.CopperHalberdItem;
import net.mcreator.maxarmory.item.CopperGuduoItem;
import net.mcreator.maxarmory.item.ChainArmorPieceItem;
import net.mcreator.maxarmory.MaxArmoryMod;

public class MaxArmoryModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MaxArmoryMod.MODID);
	public static final RegistryObject<Item> WOODEN_HENGDAO = REGISTRY.register("wooden_hengdao", () -> new WoodenHengdaoItem());
	public static final RegistryObject<Item> STONE_HENGDAO = REGISTRY.register("stone_hengdao", () -> new StoneHengdaoItem());
	public static final RegistryObject<Item> IRON_HENGDAO = REGISTRY.register("iron_hengdao", () -> new IronHengdaoItem());
	public static final RegistryObject<Item> GOLDEN_HENGDAO = REGISTRY.register("golden_hengdao", () -> new GoldenHengdaoItem());
	public static final RegistryObject<Item> DIAMOND_HENGDAO = REGISTRY.register("diamond_hengdao", () -> new DiamondHengdaoItem());
	public static final RegistryObject<Item> NETHERITE_HENGDAO = REGISTRY.register("netherite_hengdao", () -> new NetheriteHengdaoItem());
	public static final RegistryObject<Item> WOODEN_KATANA = REGISTRY.register("wooden_katana", () -> new WoodenKatanaItem());
	public static final RegistryObject<Item> STONE_KATANA = REGISTRY.register("stone_katana", () -> new StoneKatanaItem());
	public static final RegistryObject<Item> IRON_KATANA = REGISTRY.register("iron_katana", () -> new IronKatanaItem());
	public static final RegistryObject<Item> GOLDEN_KATANA = REGISTRY.register("golden_katana", () -> new GoldenKatanaItem());
	public static final RegistryObject<Item> DIAMOND_KATANA = REGISTRY.register("diamond_katana", () -> new DiamondKatanaItem());
	public static final RegistryObject<Item> NETHERITE_KATANA = REGISTRY.register("netherite_katana", () -> new NetheriteKatanaItem());
	public static final RegistryObject<Item> WOODEN_SHAMSHIR = REGISTRY.register("wooden_shamshir", () -> new WoodenShamshirItem());
	public static final RegistryObject<Item> STONE_SHAMSHIR = REGISTRY.register("stone_shamshir", () -> new StoneShamshirItem());
	public static final RegistryObject<Item> IRON_SHAMSHIR = REGISTRY.register("iron_shamshir", () -> new IronShamshirItem());
	public static final RegistryObject<Item> GOLDEN_SHAMSHIR = REGISTRY.register("golden_shamshir", () -> new GoldenShamshirItem());
	public static final RegistryObject<Item> DIAMOND_SHAMSHIR = REGISTRY.register("diamond_shamshir", () -> new DiamondShamshirItem());
	public static final RegistryObject<Item> NETHERITE_SHAMSHIR = REGISTRY.register("netherite_shamshir", () -> new NetheriteShamshirItem());
	public static final RegistryObject<Item> WOODEN_SPEAR = REGISTRY.register("wooden_spear", () -> new WoodenPikeItem());
	public static final RegistryObject<Item> STONE_SPEAR = REGISTRY.register("stone_spear", () -> new StonePikeItem());
	public static final RegistryObject<Item> IRON_SPEAR = REGISTRY.register("iron_spear", () -> new IronPikeItem());
	public static final RegistryObject<Item> GOLDEN_SPEAR = REGISTRY.register("golden_spear", () -> new GoldenPikeItem());
	public static final RegistryObject<Item> DIAMOND_SPEAR = REGISTRY.register("diamond_spear", () -> new DiamondPikeItem());
	public static final RegistryObject<Item> NETHRITE_SPEAR = REGISTRY.register("nethrite_spear", () -> new NethritePikeItem());
	public static final RegistryObject<Item> WOODEN_LONG_SWORD = REGISTRY.register("wooden_long_sword", () -> new WoodenLongSwordItem());
	public static final RegistryObject<Item> STONE_LONG_SWORD = REGISTRY.register("stone_long_sword", () -> new StoneLongSwordItem());
	public static final RegistryObject<Item> IRON_LONG_SWORD = REGISTRY.register("iron_long_sword", () -> new IronLongSwordItem());
	public static final RegistryObject<Item> GOLDEN_LONG_SWORD = REGISTRY.register("golden_long_sword", () -> new GoldenLongSwordItem());
	public static final RegistryObject<Item> DIAMOND_LONG_SWORD = REGISTRY.register("diamond_long_sword", () -> new DiamondLongSwordItem());
	public static final RegistryObject<Item> NETHERITE_LONG_SWORD = REGISTRY.register("netherite_long_sword", () -> new NetheriteLongSwordItem());
	public static final RegistryObject<Item> WOODEN_HALBERD = REGISTRY.register("wooden_halberd", () -> new WoodenHalberdItem());
	public static final RegistryObject<Item> STONE_HALBERD = REGISTRY.register("stone_halberd", () -> new StoneHalberdItem());
	public static final RegistryObject<Item> IRON_HALBERD = REGISTRY.register("iron_halberd", () -> new IronHalberdItem());
	public static final RegistryObject<Item> GOLDEN_HALBERD = REGISTRY.register("golden_halberd", () -> new GoldenHalberdItem());
	public static final RegistryObject<Item> DIAMOND_HALBERD = REGISTRY.register("diamond_halberd", () -> new DiamondHalberdItem());
	public static final RegistryObject<Item> NETHERITE_HALBERD = REGISTRY.register("netherite_halberd", () -> new NetheriteHalberdItem());
	public static final RegistryObject<Item> WOODEN_HAMMER = REGISTRY.register("wooden_hammer", () -> new WoodenHammerItem());
	public static final RegistryObject<Item> STONE_HAMMER = REGISTRY.register("stone_hammer", () -> new StoneHammerItem());
	public static final RegistryObject<Item> IRON_HAMMER = REGISTRY.register("iron_hammer", () -> new IronGuduoItem());
	public static final RegistryObject<Item> GOLDEN_HAMMER = REGISTRY.register("golden_hammer", () -> new GoldenGuduoItem());
	public static final RegistryObject<Item> DIAMOND_HAMMER = REGISTRY.register("diamond_hammer", () -> new DiamondGuduoItem());
	public static final RegistryObject<Item> NETHERITE_HAMMER = REGISTRY.register("netherite_hammer", () -> new NetheriteGuduoItem());
	public static final RegistryObject<Item> WOODEN_MACHETE = REGISTRY.register("wooden_machete", () -> new WoodenMacheteItem());
	public static final RegistryObject<Item> STONE_MACHETE = REGISTRY.register("stone_machete", () -> new StoneMacheteItem());
	public static final RegistryObject<Item> IRON_MACHETE = REGISTRY.register("iron_machete", () -> new IronMacheteItem());
	public static final RegistryObject<Item> GOLDEN_MACHETE = REGISTRY.register("golden_machete", () -> new GoldenMacheteItem());
	public static final RegistryObject<Item> DIAMOND_MACHETE = REGISTRY.register("diamond_machete", () -> new DiamondMacheteItem());
	public static final RegistryObject<Item> NETHERITE_MACHETE = REGISTRY.register("netherite_machete", () -> new NetheriteMacheteItem());
	public static final RegistryObject<Item> COPPER_HENGDAO = REGISTRY.register("copper_hengdao", () -> new CopperHengdaoItem());
	public static final RegistryObject<Item> COPPER_KATANA = REGISTRY.register("copper_katana", () -> new CopperKatanaItem());
	public static final RegistryObject<Item> COPPER_SHAMSHIR = REGISTRY.register("copper_shamshir", () -> new CopperShamshirItem());
	public static final RegistryObject<Item> COPPER_SPEAR = REGISTRY.register("copper_spear", () -> new CopperPikeItem());
	public static final RegistryObject<Item> COPPER_LONG_SWORD = REGISTRY.register("copper_long_sword", () -> new CopperLongSwardItem());
	public static final RegistryObject<Item> COPPER_HALBERD = REGISTRY.register("copper_halberd", () -> new CopperHalberdItem());
	public static final RegistryObject<Item> COPPER_HAMMER = REGISTRY.register("copper_hammer", () -> new CopperGuduoItem());
	public static final RegistryObject<Item> COPPER_MACHETE = REGISTRY.register("copper_machete", () -> new CopperMacheteItem());
	public static final RegistryObject<Item> LAMELLAR_ARMOR_HELMET = REGISTRY.register("lamellar_armor_helmet", () -> new LamellarArmorItem.Helmet());
	public static final RegistryObject<Item> LAMELLAR_ARMOR_CHESTPLATE = REGISTRY.register("lamellar_armor_chestplate", () -> new LamellarArmorItem.Chestplate());
	public static final RegistryObject<Item> LAMELLAR_ARMOR_LEGGINGS = REGISTRY.register("lamellar_armor_leggings", () -> new LamellarArmorItem.Leggings());
	public static final RegistryObject<Item> LAMELLAR_ARMOR_BOOTS = REGISTRY.register("lamellar_armor_boots", () -> new LamellarArmorItem.Boots());
	public static final RegistryObject<Item> MINGGUANG_ARMOR_HELMET = REGISTRY.register("mingguang_armor_helmet", () -> new MingguangArmorItem.Helmet());
	public static final RegistryObject<Item> MINGGUANG_ARMOR_CHESTPLATE = REGISTRY.register("mingguang_armor_chestplate", () -> new MingguangArmorItem.Chestplate());
	public static final RegistryObject<Item> HANDLE = REGISTRY.register("handle", () -> new GripItem());
	public static final RegistryObject<Item> ROD = REGISTRY.register("rod", () -> new LongGripItem());
	public static final RegistryObject<Item> LAMELLAR_ARMOR_PIECE = REGISTRY.register("lamellar_armor_piece", () -> new LamellarArmourPieceItem());
	public static final RegistryObject<Item> CHAIN_ARMOR_PIECE = REGISTRY.register("chain_armor_piece", () -> new ChainArmorPieceItem());
	public static final RegistryObject<Item> COPPER_SWORD = REGISTRY.register("copper_sword", () -> new CopperSwordItem());
}
